"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/navbar";
import Footer from "./components/footer";
import { usePathname } from "next/navigation";
import { useEffect, useState } from "react";
import SplashScreen from "./components/splash";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const isHome = pathname === "/";
  const [isLoading, setIsLoading] = useState(isHome);
  useEffect(()=> {
    console.log('====================================');
    console.log(isLoading);
    console.log('====================================');
  }, [isLoading])
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        {isLoading && isHome ? (
          <SplashScreen endLoading={() => setIsLoading(false)} />
        ) : (
          <>
            <NavBar />
            <div className="grow">{children}</div>
            <Footer />
          </>
        )}
      </body>
    </html>
  );
}
